gentoo/devmanual

- ebuild-writing/functions/pkg_pretend/text.xml
Proof: Create a dummy ebuild with
```
pkg_pretend() {
echo "Calling pkg_pretend()..."
}
```
Now create the binary package:
```
These are the packages that would be built, in order:
Calculating dependencies... done!
[ebuild  N    *] app-misc/testpkg-0.0.1::my-overlay  0 KiB
Total: 1 package (1 new), Size of downloads: 0 KiB
>>> Verifying ebuild manifests
>>> Running pre-merge checks for app-misc/testpkg-0.0.1
Calling pkg_pretend()...
[...]
```
When you now install the binary package, pkg_pretend() will be called again:
```
These are the packages that would be merged, in order:
Calculating dependencies... done!
[binary  N    *] app-misc/testpkg-0.0.1::my-overlay  0 KiB
Total: 1 package (1 new, 1 binary), Size of downloads: 0 KiB
Would you like to merge these packages? [Yes/No] y
>>> Running …
```
> pkg_pretend: Binary packages also call this function

- ebuild-writing/file-format/text.xml
Using of `$(portageq portdir)/header.txt` throws warning:
> WARNING: 'portageq portdir' is deprecated. Use the get_repo_path command instead. eg: 'portageq get_repo_path / gentoo' instead.
> Update bash command

- ebuild-writing/functions/src_prepare/epatch/text.xml
- ebuild-writing/functions/src_prepare/text.xml
- ebuild-writing/using-eclasses/text.xml
- general-concepts/autotools/text.xml
- general-concepts/dependencies/text.xml
Most of occurrence of the EAPI declarations are without the quotes, so align
the rest for more consistency.
> Consistent EAPI declaration

- Makefile
- devbook.dtd
- devbook.xsl
- general-concepts/autotools/text.xml
- general-concepts/emerge-and-ebuild/text.xml
- general-concepts/git-to-rsync/text.xml
- general-concepts/mirrors/text.xml
This series of patches is a first attempt to fix the structure of the devmanual. I mainly went by what is actually supported by `devbook.xsl`, and I've changed or dropped those elements and attributes that aren't.
I've also written a preliminary [devbook.dtd](https://gist.github.com/ulm/871338b513483ce0ff45e12295aacfb1) and all files of the document validate with it:
`xmllint --noout --dtdvalid devbook.dtd text.xml`
As is to be expected for a project that has been developed since 10+ years without any formal verification, the resulting rules aren't very strict. For example, there can be formatting elements inside `<title>` when there really shouldn't be, and almost everything is allowed below `<li>` or `<ti>`. We might think about tightening the rules in a second round of updates.
> Fix XML structure

- bin/gen-eclass-html.sh
- devbook.dtd
- devbook.xsl
This replaces &lt;list-group-d&gt;, which was only used for the list of
eclasses. Remove &lt;list-group-u&gt; which was unused.
Update devbook.dtd and bin/gen-eclass-html.sh accordingly.
Generated output in eclass-reference/index.html is identical as
before, except for an (intentionally) removed empty line before the
closing &lt;/div&gt;.
> devbook.xsl: Support class="list-group" in <ul> element.

- appendices/common-problems/text.xml
- appendices/contributing/devbook-guide/text.xml
- appendices/contributing/text.xml
- appendices/further-reading/text.xml
- archs/amd64/text.xml
- devbook.dtd
- devbook.xsl
- devmanual.css
- ebuild-writing/eapi/text.xml
- general-concepts/tree/text.xml
- keywording/text.xml
- tools-reference/tr/text.xml
Definition lists required only `p` elements as children of `dd`. Change to a more conventional syntax where each `dt` element can be followed by one **or more** `dd` elements.
> More conventional syntax of definition lists

- ebuild-writing/eapi/text.xml
- ebuild-writing/functions/src_compile/text.xml
Section, subsection, etc. titles are used to construct ID attributes,
which must be unique within each chapter.
One approach to disambiguate these identifiers would be to use the
complete section hierarchy for constructing them (see bug 626032).
However, that would break external references (and for example, links
from bugzilla or from mailing list archives cannot be updated).
Use a less intrusive approach instead and make the titles of the few
ambiguous subsections unique, or convert them to a list.
Closes: https://bugs.gentoo.org/626032
> Make (sub-)section titles unique within each chapter.

- devbook.xsl
Keep only characters that HTML 4 allows in ID attributes (but exclude the colon as well). Note that HTML 5 is more sloppy and would permit characters outside of the ASCII range, but these won't be valid in URI fragment identifiers (RFC 3986).
> ID attributes should contain only valid characters.

- tools-reference/cut/text.xml
- tools-reference/head-and-tail/text.xml
Having recently seen some bad code convinces me that we shouldn't drop the "head and tail" section.
This adds another (quite horrible) example.
> Head and tail

- Makefile
- bin/gen-eclass-html.sh
Running "tidy" on the html files generated from eclass manpages produced several warnings. Add some additional postprocessing to reduce their number.
Some warnings for `fortran-2.eclass` and `multilib-build.eclass` remain. They are caused by malformed eclass documentation (already fixed in the tree) and should go away after the next release of app-doc/eclass-manpages.
> More postprocessing of man2html output

- appendices/editor-configuration/text.xml
This no longer applies, ebuild specific sections have been removed from nanorc in 2015.
> appendices/editor-configuration: Drop outdated to-do item.

- devmanual.css
Most elements of the stylesheet are either not used at all, or they are superseded by the Bootstrap or Tyrian stylesheets which are loaded later.
> devmanual.css: Drop unused elements.

- appendices/contributors/text.xml
- bin/gen-eclass-html.sh
- devbook.xsl
- ebuild-writing/functions/src_compile/build-environment/text.xml
- ebuild-writing/functions/src_compile/building/text.xml
- ebuild-writing/functions/src_unpack/svn-sources/text.xml
- ebuild-writing/using-eclasses/text.xml
- tasks-reference/completion/text.xml
Fix links to eclass reference pages, which wasn't working since the transition to auto-generated pages.
This allows to revert the earlier workaround that had changed all references in the text.
> Links to eclass references

- Makefile
- bin/gen-eclass-html.sh
- devbook.xsl
- offline.css
Pass a `fallback` flag to devbook.xsl, which disables loading of external assets and loads a simple CSS instead. This will replace the fragile patching in the `app-doc/devmanual` ebuild.
Question for reviewers, should I also remove the division containing:
> ### Questions or comments?
> Please feel free to [contact us](https://www.gentoo.org/inside-gentoo/contact/).
from the footer? The offline package currently displays it, but IMHO it looks strange in the offline version.
> Support offline browsing

- Makefile
- appendices/contributing/text.xml
As discussed in #gentoo-qa. This will allow to much simplify the app-doc/devmanual ebuild.
On the long term, it will enable infra to install into a separate target directory.
> Makefile: Add install target.

- ebuild-writing/variables/text.xml
- general-concepts/slotting/text.xml
Not sure from where the concept "an empty slot means disable slotting" originated. In any case, it is wrong, and it was not legal in any EAPI.
> general-concepts/slotting: Clarify that SLOT must not be empty.

- devbook.xsl
This aims at improving navigation by also listing the sections of the current chapter in the dropdown list.
As before, list any first-level sub-documents (below a divider line).
> devbook.xsl: List sections in navigation dropdown.

- .gitignore
- Makefile
- depend.xsl
- devbook.xsl
Each HTML file must depend on its XML file with all its descendants (for the contents tree), all its ancestors (for breadcrumbs), and the previous and next documents (for backward and forward links).
Trying to generate the list of dependencies with make seems hopeless (especially, how would one determine the previous and next documents?). OTOH, the necessary templates already exist in devbook.xsl. Therefore, add a simple depend.xsl on top of it, which outputs a dependency list as plain text.
Closes: https://bugs.gentoo.org/710918
> Makefile, depend.xsl: Use XSLT to generate the list of dependencies.

- appendices/common-problems/text.xml
- archs/alpha/text.xml
- archs/amd64/text.xml
- archs/mips/text.xml
- archs/ppc/text.xml
- archs/sparc/text.xml
- archs/x86/text.xml
- general-concepts/overlay/text.xml
- tools-reference/bash/text.xml
- tools-reference/cat/text.xml
- tools-reference/cut/text.xml
- tools-reference/diff-and-patch/text.xml
- tools-reference/echo/text.xml
- tools-reference/ekeyword/text.xml
- tools-reference/false-and-true/text.xml
- tools-reference/find/text.xml
- tools-reference/grep/text.xml
- tools-reference/head-and-tail/text.xml
- tools-reference/sed/text.xml
- tools-reference/sort/text.xml
- tools-reference/tr/text.xml
- tools-reference/uniq/text.xml
Replace -- in titles by em-dashes throughout, except for QA notices in appendices/common-problems where it is replaced by a colon (which is what the actual QA notices have).
> Use unicode em-dash in titles.

- ebuild-writing/eapi/text.xml
- ebuild-writing/variables/text.xml
Many lists in this chapter simulate definition lists by:
```
<ul>
<li>
<p><b>term</b><p>
<p>definition<p>
</li>
...
</ul>
```
Change all of these to real definition lists.
Reformat the file according to the style guide.
> ebuild-writing/eapi: Reformat the lists.

- ebuild-writing/common-mistakes/text.xml
This is no longer a common mistake. Exactly the same note is still present in ebuild-writing/file-format.
> ebuild-writing/common-mistakes: Drop note on Header/Id line

- general-concepts/licenses/text.xml
By the FSF's definition (see for example GPL-3):
"The 'Corresponding Source' for a work in object code form means all the source code needed to generate, install, and (for an executable work) run the object code and to modify the work, including scripts to control those activities."
It makes much sense to apply this as a general definition. Applying it only to GPL licensed packages would mean:
- We would need another case distinction, making the rules for LICENSE even more complicated.
- As an example, consider a MIT licensed package with a CDDL licensed (i.e., GPL incompatible) build script: If that package was a library, then it couldn't be linked against a GPL licensed package, whereas a LICENSE variable listing only MIT would falsely indicate that it could.
@gentoo/licenses
> general-concepts/licenses: LICENSE should include build scripts

- appendices/contributors/text.xml
- ebuild-writing/misc-files/patches/text.xml
Taken from https://dev.gentoo.org/~vapier/clean-patches, with some rewording.
(Work in progress.)
Bug: https://bugs.gentoo.org/247266
> ebuild-writing/misc-files/patches: Add section about clean patches

- appendices/devbook-guide/text.xml
Drop the "Devbook XML" section header which was not very useful.
Instead, promote "Basic structure" from subsection to section,
and introduce two new sections "Body elements" and "Inline elements".
So, the resulting section structure is:
- DevBook XML design goals
- Basic structure
- Sections and subsections
- Including sub-documents
- An example &lt;body&gt;
- Body elements
- Code samples and colour-coding
- Figures
- Tables
- Lists
- Inline elements
- &lt;c&gt;, &lt;b&gt;, and &lt;e&gt;
- &lt;uri&gt;
- Intra-document references
- Coding Style
- Internal Coding Style
- External Coding Style
> devbook-guide: Clearer section structure

- appendices/contributors/text.xml
- ebuild-writing/eapi/text.xml
- text.xml
Main part taken from "The ultimate guide to EAPI 8" by Michał Górny:
https://mgorny.pl/articles/the-ultimate-guide-to-eapi-8.html
Converted to DevBook XML and heavily edited to make it fit into the framework of the devmanual.
Original-Author: Michał Górny <mgorny@gentoo.org>
Original-License: CC-BY-3.0
> ebuild-writing/eapi: Add EAPI 8 guide

- appendices/devbook-guide/text.xml
Apparently the underlying bug has been fixed in commit b5bfc69.
> devbook-guide: Remove warning about newlines in title element

- ebuild-writing/misc-files/metadata/text.xml
> ebuild-writing/misc-files/metadata: Replace http by https

- archs/amd64/text.xml
Profile information was way behind (2005); this updates it to 17.0 and 17.1.
@gentoo/amd64: Is the table in subsection "Libdir links" correct like this?
> archs/amd64: Update information on profiles

- bin/gen-eclass-html.sh
man2html's heuristic for recognition of e-mail addresses is
unreliable, therefore drop them all.
Reported-by: Thomas Bracht Laumann Jespersen <t@laumann.xyz>
> bin/gen-eclass-html.sh: Don't show mailto links

- ebuild-writing/misc-files/metadata/text.xml
This corresponds to the update of GLEP 68.
Bug: https://bugs.gentoo.org/578294
> ebuild-writing/misc-files/metadata: Language tags can be BCP 47

- general-concepts/config-protect/text.xml
Bug: https://bugs.gentoo.org/289565
[Make the XML validate. Small tweaks to example and wording.]
> general-concepts/config-protect: Add example for env.d

- tools-reference/bash/text.xml
Parts of this have been taken from the Bash Reference Manual authored by
Chet Ramey and Brian Fox. See https://bugs.gentoo.org/829916#c9.
Closes: https://bugs.gentoo.org/829916
Reported-by: Alexis <flexibeast@gmail.com>
> tools-reference/bash: Add tables of metacharacters and constructs

- devbook.xsl
Eclasses are licensed GPL-2, therefore we need a different footer.
Hardcode this for all sub-pages of eclass-reference/.
Signed-off-by: Ulrich Müller &lt;ulm@gentoo.org&gt;
> devbook.xsl: Eclass documentation needs GPL-2 in the footer

- ebuild-writing/eapi/text.xml
The former is semi-deprecated and we shouldn't advertise its use.
> ebuild-writing/eapi: Replace interactive by live in example

- general-concepts/ebuild-revisions/text.xml
Note that when adding a USE flag where the functionality was previously on
(not off in build system), one must revbump
because a dep was unconditional that now became conditional.
Also, if removing a USE flag where the behaviour is now on, but was previously
always off (not on in build system), one must revbump also,
because people might have never set USE=foo (hence --changed-use wouldn't pick
it up) but their deps have now effectively changed.
Bug: https://github.com/pkgcore/pkgcheck/pull/435
Signed-off-by: Sam James <sam@gentoo.org>
> general-concepts/ebuild-revisions: clarify interaction with adding/removing USE flags

- function-reference/install-functions/text.xml
As a followup to the previous change, use a better path for the example and reword. No longer mention EAPI 7 because all older EAPIs are deprecated.
> function-reference/install-functions: Reword dostrip documentation

- function-reference/query-functions/text.xml
Closes: https://bugs.gentoo.org/914590
> function-reference/query-functions: usev accepts two args in EAPI 8

- devbook.xsl
If the element that is extracted from the external document contains internal references, these links would be relative to the wrong start location, namely the one defined in that document. Therefore, define our own copy of /guide/@self (pointing to the location of the target document), and rebase the tree onto it.
This fixes the intra-document links in appendices/todo-list/.
Closes: https://bugs.gentoo.org/916523
> devbook.xsl: Fix links created by contentsTree extraction

- appendices/devbook-guide/text.xml
Reiterating PR #298. Even if we focus more on Bugzilla for organising our work, this shouldn't stop us from documenting DevBook XML elements that are used in the document source.
> appendices/devbook-guide: Document the todo element

- .gitignore
- appendices/contributors/text.xml
- ebuild-writing/functions/src_prepare/eapply/text.xml
- ebuild-writing/functions/src_prepare/text.xml
- quickstart/text.xml
- tools-reference/diff-and-patch/text.xml
- xsl/lang.highlight.ebuild.xsl
Take 2, completely reworked (instead of #329 which was too simplistic).
> Drop epatch command and rework eapply explanation

- general-concepts/licenses/text.xml
Historically we had some PDF files in the repository, but the last of them was removed in 2011.
> general-concepts/licenses: Licenses must be plain text

- ebuild-writing/messages/text.xml
- function-reference/message-functions/text.xml
No longer mention eutils.eclass for eqawarn.
> ebuild-writing, function-reference: Update eqawarn documentation

- Makefile
This had been added in commit aa6e1e365fff48b6e1e5470791f499a0589d39c3, so that app-doc/devmanual[offline] could call "emake build" without building documents.js. This is no longer needed; the offline condition can be tested by the Makefile itself.
Drop validate as prerequisite of all because it required libxml2 as additional build dependency.
> Makefile: Remove the separate "build" target

- appendices/devbook-guide/text.xml
- general-concepts/slotting/text.xml
This is a section I've been wanting to write for quite some time and formalises a talk I've had to give many contributors.
Slotting is a powerful tool but easy to abuse and there's a number of non-obvious pitfalls that we should document: attempt to do that here.
> general-concepts/slotting: New 'Considerations for slotting' section

- appendices/devbook-guide/text.xml
There's sometimes confusion about syntax of intra-document refs (most recently in #366). Add a clarification to the devbook guide.
> devbook-guide: Clarify syntax of intra-document references

- appendices/further-reading/text.xml
Refer to both the QA Policy Guide and the Package Manager Specification.
I often recommend new contributors read and familiarise themselves with both.
Closes: https://bugs.gentoo.org/720880
> appendices/further-reading: add 'Gentoo documents' section
