- quickstart/text.xml
Using the new header according to git migration and bump EAPI to latest.
> Quickstart guide update

- general-concepts/git-to-rsync/diagram.svg
- general-concepts/git-to-rsync/text.xml
- general-concepts/mirrors/text.xml
- general-concepts/text.xml
> Replace cvs to rsync with git to rsync

- ebuild-writing/common-mistakes/text.xml
- ebuild-writing/eapi/text.xml
- ebuild-writing/file-format/text.xml
- ebuild-writing/functions/src_prepare/epatch/text.xml
- ebuild-writing/functions/src_unpack/rpm-sources/text.xml
- ebuild-writing/using-eclasses/text.xml
- eclass-writing/text.xml
Due to git migration.
Depends on #31.
> Update header lines

- tools-reference/diff-and-patch/text.xml
Adding git, when it was written cvs and svn were realy popular.
> Diff and patch update

- ebuild-writing/eapi/text.xml
See https://bugs.gentoo.org/show_bug.cgi?id=565582
> EAPI 6 needs to be documented

- ebuild-writing/functions/src_prepare/text.xml
Not really happy with the conditional patching in the sample, but modernize at least
> ebuild-writing/functions/src_prepare: modernize src_prepare()

- devbook.xsl
> devbook.xsl: Fix handling of <uri> without link attribute.

- ebuild-writing/functions/src_install/text.xml
- function-reference/build-functions/text.xml
I have this small update in a local branch since 2015, but for some reason never submitted it for review.
> ebuild-writing/functions/src_install: Don't mention einstall.

- ebuild-maintenance/text.xml
- general-concepts/package-collisions/text.xml
- general-concepts/text.xml
This section is about a general concept, not a particular maintenance operation.
> general-concepts/package-collisions: Moved here from ebuild-maintenance.

- Makefile
After the "maintenance-tasks" subsection was split up some time ago, the generated HTML file for it still exists: https://devmanual.gentoo.org/ebuild-maintenance/maintenance-tasks/index.html
So, delete any orphaned html and image files that could be left over after the corresponding source file was moved or removed. Such files are also not covered by `clean`, so add the new target as prerequisite.
Run a single `find` pass to get a list of all files in `ALL_FILES` and subsequently extract the necessary subsets from it. The list of all files is needed anyway for deletion of orphans, which are not included in `HTMLS` or `IMAGES`.
> Makefile: New target "delete-old"

- ebuild-writing/eapi/text.xml
- ebuild-writing/functions/src_install/text.xml
- ebuild-writing/functions/src_prepare/text.xml
This follows the recent PMS update:
https://gitweb.gentoo.org/proj/pms.git/commit/?id=0d4ffd51d3dc86782dae2db9fe632f45af7eec87
> Sync example phase functions from PMS.

- bin/gen-eclass-html.sh
The new strict dependencies will cause the build to fail if eclass-reference/text.xml is missing, because it is needed as a dependency for index.html of the previous and next documents. Add an option that makes it possible to create the file, even if the eclass documentation is missing.
> bin/gen-eclass-html.sh: New option -n to create a placeholder file.

- ebuild-writing/file-format/text.xml
Discussion reference: https://archives.gentoo.org/gentoo-dev/message/8dadfbd3c15b6580abb84882e9115a47 and replies.
> New subsection for binary packages

- devbook.xsl
- devmanual.css
See [bug 772005](https://bugs.gentoo.org/772005).
> Add permalinks to section headers

- eclass-writing/text.xml
> eclass-writing: @DEAD must be the first tag

- general-concepts/copyright-policy/text.xml
Include an explicit list of licenses from GLEP 76.
Other small touchups.
> Copyright policy

- bin/gen-eclass-html.sh
- devbook.xsl
Bug: https://bugs.gentoo.org/613938
> devbook.xsl, bin/gen-eclass-html.sh: Link to privacy policy

- function-reference/install-functions/text.xml
Closes: https://bugs.gentoo.org/916017
> function-reference/install-functions: Mention dosym -r option

- ebuild-writing/functions/src_install/text.xml
- ebuild-writing/variables/text.xml
- general-concepts/licenses/text.xml
- general-concepts/overlay/text.xml
Closes: https://bugs.gentoo.org/865455
> No longer mention PORTDIR

- general-concepts/tree/text.xml
> general-concepts/tree: Allow @ in filenames

- devbook.xsl
- Separate finding the node from HTML formatting.
- Determine the absolute parent path from the path of our own `@self` attribute, rather than from the parent document's `@self` attribute.
- Get the first node from the following-sibling or preceding-sibling axis directly, instead of laboriously calculating its index.
> devbook.xsl: Rework templates for previous/next node

- general-concepts/ebuild-revisions/text.xml
> general-concepts/ebuild-revisions: Almost always revbump when stable

- ebuild-writing/eapi/text.xml
- ebuild-writing/file-format/text.xml
- ebuild-writing/variables/text.xml
- function-reference/install-functions/text.xml
- function-reference/version-functions/text.xml
- profiles/text.xml
Other small updates of wording (when in the same paragraph). Fix/update some external links.
> Refer to the Package Manager Specification by its full name
